### ISSUE TITLE
ChannelSettings - Problem

### ISSUE THREAD

**Issue by mimol91** [RafPe/massive-color#2]
When I am trying to compile I got 
`The type or namespace name 'ChannelSettings' could not be found (are you missing a using directive or an assembly reference?)  Massive_Color\Internal\ApplicationProfile.cs    18  16  Massive_Color`
What can be a reason?

Similar for 
`Error  10  'RafTech.Graphics.RGCapture.x64.RGBdata' does not contain a definition for 'AverageScreen' and no extension method 'AverageScreen' accepting a first argument of type 'RafTech.Graphics.RGCapture.x64.RGBdata' could be found (are you missing a using directive or an assembly reference?) Massive_Color\MainWindow.xaml.cs    118 51  Massive_Color`

**Comment by RafPe** [comment]
Seems like the following line https://github.com/RafPe/massive-color/blob/master/Massive_Color/MainWindow.xaml.cs#L136 

should be using the following method from https://github.com/RafPe/massive-color/blob/master/RafTech.Graphics.RGCapture.x64/RGBdata.cs#L50 

Can you adjust in your repo and if works make a PR ?

**Comment by mimol91** [comment]
Sure I ll try to do it when got some free time.
The problem is that I 've to remove `IntelliLock.Licensing` from project. Is it OK for you as it tends to be open-source project?

**Comment by RafPe** [comment]
This is now opensource project completly - so feel free to remove any references to this library/code
